# -*- coding: utf-8 -*-
import sys; sys.stdout.reconfigure(encoding='utf-8')

# Big Day 8: words 1202-1380
bd8 = [
(1202,"array","n./v.","/@'reI/","阵列；排列；★大量","A vast array of products is displayed in the showroom."),
(1203,"arrogant","adj.","/'Ar@g@nt/","傲慢的","His arrogant attitude made him unpopular with colleagues."),
(1204,"articulate","adj./v.","/A:r'tIkj@leIt/","善于表达的；清晰表达","She can articulate complex ideas in simple terms."),
(1205,"ascend","v.","/@'send/","上升；攀登","The path ascends steeply through the pine forest."),
(1206,"ascertain","v.","/As@r'teIn/","查明；确定","Police are trying to ascertain the cause of the fire."),
(1207,"aspect","n.","/'Aspekt/","方面；外观","Climate change affects every aspect of our lives."),
(1208,"aspire","v.","/@'spaI@r/","渴望；有志于","She aspires to become a world-class surgeon."),
(1209,"assault","n./v.","/@'sO:lt/","攻击；袭击","He was charged with assault after the bar fight."),
(1210,"assert","v.","/@'s3:rt/","断言；★维护","He continued to assert his innocence at the trial."),
(1211,"asset","n.","/'Aset/","资产；★优点","Her language skills are a great asset to the company."),
(1212,"assimilate","v.","/@'sImIleIt/","吸收；★同化","Immigrants often struggle to assimilate into a new culture."),
(1213,"assure","v.","/@'SUr/","保证；使确信","I can assure you the product is completely safe."),
(1214,"attitude","n.","/'AtItu:d/","态度；看法","A positive attitude is essential for success."),
(1215,"attorney","n.","/@'t3:rni/","律师","The defendant refused to speak without his attorney."),
(1216,"attract","v.","/@'trAkt/","吸引","Low taxes are designed to attract foreign investment."),
(1217,"auction","n./v.","/'O:kS@n/","拍卖","The painting was sold at auction for $110 million."),
(1218,"audience","n.","/'O:di@ns/","观众；听众","The speaker captured the audience's attention instantly."),
(1219,"augment","v.","/O:g'ment/","增加；扩大","She augmented her income by teaching evening classes."),
(1220,"authentic","adj.","/O:'TentIk/","真实的；可信的","The restaurant serves authentic Sichuan cuisine."),
(1221,"authoritative","adj.","/@'TO:rIteItIv/","权威的","The book is the authoritative text on the subject."),
(1222,"authority","n.","/@'TO:r@ti/","权威；★当局","The local authority maintains public parks."),
(1223,"automate","v.","/'O:t@meIt/","使自动化","The factory has been fully automated."),
(1224,"autonomous","adj.","/O:'tA:n@m@s/","自治的","The region was granted autonomous status."),
(1225,"avail","v./n.","/@'veIl/","利用；效用","He availed himself of the opportunity to study abroad."),
(1226,"available","adj.","/@'veIl@b@l/","可获得的；有空的","Is the manager available to take a call?"),
(1227,"avenue","n.","/'Av@nu:/","大街；★途径","The internet opened new avenues for learning."),
(1228,"average","adj./n./v.","/'Av@rIdZ/","平均的；平均数","The average temperature in July is 30 degrees."),
(1229,"avert","v.","/@'v3:rt/","避免；★转移","The disaster was narrowly averted by firefighters."),
(1230,"avoid","v.","/@'vOId/","避免","Please read the instructions to avoid confusion."),
(1231,"await","v.","/@'weIt/","等待","A warm welcome awaits all visitors."),
(1232,"awake","adj./v.","/@'weIk/","醒着的；唤醒","The noise kept me awake all night."),
(1233,"award","n./v.","/@'wO:rd/","奖；授予","She was awarded the Nobel Prize for her research."),
(1234,"aware","adj.","/@'wer/","意识到的","Are you aware of the risks involved?"),
(1235,"awe","n./v.","/O:/","敬畏；使敬畏","We stood in awe of the magnificent mountain range."),
(1236,"awkward","adj.","/'O:kw@rd/","尴尬的；笨拙的","There was an awkward silence after his remark."),
(1237,"back","n./adj./v.","/bAk/","背部；★支持；回","The board unanimously backed the expansion plan."),
(1238,"background","n.","/'bAkgrAund/","背景","Applicants with a scientific background are preferred."),
(1239,"backward","adj./adv.","/'bAkw@rd/","向后的；★落后的","Infrastructure in this region is still backward."),
(1240,"bacterium","n.","/bAk'tIri@m/","细菌","The infection is caused by a type of bacterium."),
(1241,"badge","n.","/bAdZ/","徽章；标志","All employees must wear an identification badge."),
(1242,"bake","v.","/beIk/","烘烤","She baked a chocolate cake for her son's birthday."),
(1243,"balance","n./v.","/'bAl@ns/","平衡；使平衡","Finding a balance between work and life is hard."),
(1244,"balcony","n.","/'bAlk@ni/","阳台","They enjoyed coffee on the balcony overlooking the sea."),
(1245,"ballot","n./v.","/'bAl@t/","选票；投票","Union members will ballot on the pay offer."),
(1246,"ban","v./n.","/bAn/","禁止；禁令","The government banned smoking in public places."),
(1247,"band","n.","/bAnd/","乐队；★带；★波段","A rubber band held the papers together."),
(1248,"bankrupt","adj./v.","/'bANkr^pt/","破产的；使破产","The company went bankrupt after losing its biggest client."),
(1249,"banner","n.","/'bAn@r/","横幅；旗帜","Protesters carried banners demanding climate action."),
(1250,"bar","n./v.","/bA:r/","酒吧；★条；★禁止","He was barred from entering the country."),
(1251,"bare","adj.","/ber/","赤裸的；★仅有的","The room was bare except for a single chair."),
(1252,"bargain","n./v.","/'bA:rg@n/","便宜货；★讨价还价","She picked up a real bargain at the flea market."),
(1253,"barrel","n.","/'bAr@l/","桶","The price of a barrel of oil has fallen sharply."),
(1254,"barrier","n.","/'bAri@r/","障碍；屏障","Language is a major barrier for immigrants."),
(1255,"basement","n.","/'beIsm@nt/","地下室","The laundry room is in the basement."),
(1256,"beam","n./v.","/bi:m/","光束；★微笑","She beamed with pride as her daughter collected the award."),
(1257,"bear","v./n.","/ber/","忍受；★承担；熊","The company will bear all costs of the move."),
(1258,"beat","v./n.","/bi:t/","打；★击败；节拍","Our team beat the defending champions 3-0."),
(1259,"behalf","n.","/bI'hAf/","代表(on behalf of)","I am writing on behalf of all the residents."),
(1260,"behave","v.","/bI'heIv/","表现；★守规矩","The children behaved well throughout the ceremony."),
(1261,"belly","n.","/'beli/","腹部","He complained of a sharp pain in his belly."),
(1262,"beloved","adj.","/bI'l^vd/","心爱的","She was a beloved teacher for generations of students."),
(1263,"bend","v./n.","/bend/","弯曲；弯道","The road bends sharply after the bridge."),
(1264,"beneath","prep.","/bI'ni:T/","在…之下","Ancient ruins lie beneath the modern city."),
(1265,"beneficial","adj.","/benI'fIS@l/","有益的","Exercise is beneficial for both body and mind."),
(1266,"betray","v.","/bI'treI/","背叛；★泄露","His expression betrayed his true feelings."),
(1267,"bewilder","v.","/bI'wIld@r/","使困惑","The complex legal terms bewildered the defendant."),
(1268,"bias","n./v.","/'baI@s/","偏见；使有偏见","The study was criticized for its Western bias."),
(1269,"bid","v./n.","/bId/","出价；★努力","The company made a hostile bid for its competitor."),
(1270,"bind","v.","/baInd/","捆绑；★约束","The contract legally binds both parties."),
(1271,"biography","n.","/baI'A:gr@fi/","传记","She is writing a biography of the civil rights leader."),
(1272,"bizarre","adj.","/bI'zA:r/","奇怪的","The film tells a bizarre story about dreams and reality."),
(1273,"blade","n.","/bleId/","刀片；叶片","Turbine blades spin at over 3,000 rpm."),
(1274,"blame","v./n.","/bleIm/","责怪；责任","He refused to take the blame for others' mistakes."),
(1275,"blast","n./v.","/blAst/","爆炸；★猛烈抨击","The explosion blasted a hole in the building."),
(1276,"blaze","n./v.","/bleIz/","大火；熊熊燃烧","Firefighters battled the blaze for six hours."),
(1277,"bleed","v.","/bli:d/","流血","The wound was bleeding heavily."),
(1278,"blend","v./n.","/blend/","混合；混合物","The design blends tradition with modern technology."),
(1279,"bless","v.","/bles/","祝福","We are blessed to live in such a beautiful place."),
(1280,"block","n./v.","/blA:k/","街区；★阻挡","A fallen tree was blocking the entire road."),
(1281,"bloom","v./n.","/blu:m/","开花；花","Cherry trees bloom in early April each year."),
(1282,"blueprint","n.","/'blu:prInt/","蓝图","The architect presented the blueprint for the new center."),
(1283,"blunt","adj./v.","/bl^nt/","钝的；★直率的","To be blunt, your proposal is unrealistic."),
(1284,"board","n./v.","/bO:rd/","板；★董事会；登机","She was elected to the board of directors."),
(1285,"boast","v./n.","/boust/","吹嘘；★拥有","The city boasts one of the finest museums in the country."),
(1286,"bold","adj.","/bould/","大胆的；★粗体的","It was a bold decision that transformed the company."),
(1287,"bolt","n./v.","/boult/","螺栓；闩上","Make sure the door is bolted before you sleep."),
(1288,"bond","n./v.","/bA:nd/","纽带；★债券；建立关系","Shared experiences created a strong bond between them."),
(1289,"boom","n./v.","/bu:m/","繁荣；迅速增长","The tech boom created thousands of millionaires."),
(1290,"boost","v./n.","/bu:st/","促进；推动","Tax cuts are expected to boost consumer spending."),
(1291,"border","n./v.","/'bO:rd@r/","边界；接壤","The two countries share a 2,000km border."),
(1292,"bore","v./n.","/bO:r/","使厌烦；★钻孔","The long lecture bored most of the students."),
(1293,"bound","adj./n./v.","/baund/","必然的；★前往；界限","The train is bound for London."),
(1294,"boundary","n.","/'baundri/","分界线","The river forms a natural boundary between the provinces."),
(1295,"bow","v./n.","/bau/","鞠躬；★屈服；弓","The performer bowed to the audience after the ovation."),
(1296,"boycott","v./n.","/'bOIkA:t/","抵制；联合抵制","Consumers threatened to boycott the brand."),
(1297,"brace","v./n.","/breIs/","支撑；★准备","Brace yourself for some shocking news."),
(1298,"brand","n./v.","/brAnd/","品牌；烙印","The company is trying to rebrand itself."),
(1299,"breach","n./v.","/bri:tS/","违反；破坏","The company was fined for breach of data protection laws."),
(1300,"breakdown","n.","/'breIkdaun/","故障；崩溃","The breakdown of negotiations led to a strike."),
(1301,"breakthrough","n.","/'breIkTru:/","突破","The discovery is a major breakthrough in cancer research."),
(1302,"breed","v./n.","/bri:d/","繁殖；★导致；品种","Unemployment breeds social unrest and crime."),
(1303,"breeze","n.","/bri:z/","微风","A cool breeze made the afternoon pleasant."),
(1304,"bribe","n./v.","/braIb/","贿赂；行贿","The official was jailed for accepting bribes."),
(1305,"brick","n.","/brIk/","砖","The house is built of red brick."),
(1306,"briefcase","n.","/'bri:fkeIs/","公文包","He took documents out of his briefcase."),
(1307,"brilliant","adj.","/'brIlj@nt/","卓越的；★明亮的","She had a brilliant idea that saved the company millions."),
(1308,"brink","n.","/brINk/","边缘","The two countries are on the brink of war."),
(1309,"brisk","adj.","/brIsk/","轻快的；★兴隆的","The shop did a brisk trade during the storm."),
(1310,"broadcast","v./n.","/'brO:dkAst/","广播；节目","The interview will be broadcast live on television."),
(1311,"brochure","n.","/brou'SUp/","小册子","The agency sent a brochure about holiday destinations."),
(1312,"brook","n./v.","/brUk/","小溪；★容忍","He would brook no interference in his affairs."),
(1313,"browse","v.","/brauz/","浏览","I spent the afternoon browsing through old photos."),
(1314,"bruise","n./v.","/bru:z/","淤青；碰伤","He had several bruises after the fall."),
(1315,"bubble","n./v.","/'b^b@l/","气泡；★泡沫","The housing bubble burst in 2008."),
(1316,"budget","n./v.","/'b^dZIt/","预算；编制预算","The project was completed within budget."),
(1317,"bulk","n.","/b^lk/","大量；★体积","The bulk of the work was done by year end."),
(1318,"bull","n.","/bUl/","公牛；★上涨的","Investors are feeling bullish about the tech sector."),
(1319,"bulletin","n.","/'bUl@tIn/","公告","The company issued a bulletin to all staff."),
(1320,"bundle","n./v.","/'b^nd@l/","捆；捆绑","The software comes bundled with the operating system."),
(1321,"burden","n./v.","/'b3:rd@n/","负担；使负重","The heavy tax burden forced many businesses to close."),
(1322,"bureau","n.","/'bjUrou/","局；办事处","The weather bureau issued a storm warning."),
(1323,"bureaucracy","n.","/bjU'rA:kr@si/","官僚机构","Excessive bureaucracy slows down government decision-making."),
(1324,"burst","v./n.","/b3:rst/","爆裂；爆发","The water pipe burst, flooding the basement."),
(1325,"cabin","n.","/'kAbIn/","小屋；机舱","They rented a cozy log cabin for the weekend."),
(1326,"cabinet","n.","/'kAbIn@t/","橱柜；★内阁","The prime minister reshuffled her cabinet."),
(1327,"cable","n.","/'keIb@l/","电缆；缆绳","The bridge is supported by massive steel cables."),
(1328,"calculate","v.","/'kAlkj@leIt/","计算；★估计","We calculated the trip would cost around $2,000."),
(1329,"campaign","n./v.","/kAm'peIn/","运动；发起运动","The presidential campaign lasted nearly two years."),
(1330,"campus","n.","/'kAmp@s/","校园","The university campus covers over 200 acres."),
(1331,"candidate","n.","/'kAndIdeIt/","候选人","She is the strongest candidate for the position."),
(1332,"capable","adj.","/'keIp@b@l/","有能力的","She is capable of handling this project alone."),
(1333,"capacity","n.","/k@'pAs@ti/","能力；★容量；★身份","The stadium has a seating capacity of 80,000."),
(1334,"capture","v./n.","/'kAptS@r/","捕获；★吸引","The photo captures the beauty of the sunset."),
(1335,"carbon","n.","/'kA:rb@n/","碳","The company aims to achieve carbon neutrality by 2030."),
(1336,"carve","v.","/kA:rv/","雕刻；★开创","She carved out a successful career in a male-dominated industry."),
(1337,"casual","adj.","/'kAZu@l/","随意的；★临时的","The company relies on casual labor during harvest."),
(1338,"casualty","n.","/'kAZu@lti/","伤亡人员","The battle resulted in heavy casualties on both sides."),
(1339,"catalog","n./v.","/'kAt@lO:g/","目录；编目","The library catalog lists over two million books."),
(1340,"catastrophe","n.","/k@'tAstr@fi/","灾难","The oil spill was an environmental catastrophe."),
(1341,"category","n.","/'kAt@gO:ri/","类别","The award has several categories."),
(1342,"cater","v.","/'keIt@r/","迎合；★提供餐饮","The restaurant caters to customers with dietary restrictions."),
(1343,"caution","n./v.","/'kO:S@n/","谨慎；警告","Investors are advised to exercise caution."),
(1344,"cease","v.","/si:s/","停止","The factory ceased operations after 50 years."),
(1345,"celebrity","n.","/s@'lebr@ti/","名人","The charity event attracted Hollywood celebrities."),
(1346,"census","n.","/'sens@s/","人口普查","The census shows the population grew by 6 percent."),
(1347,"certificate","n.","/s@r'tIfIk@t/","证书","You need a medical certificate for this job."),
(1348,"certify","v.","/'s3:rtIfaI/","证明；认证","The product has been certified as organic."),
(1349,"challenge","n./v.","/'tSAl@ndZ/","挑战；质疑","New evidence challenges the accepted theory."),
(1350,"champion","n./v.","/'tSAmpi@n/","冠军；★拥护","She has championed women in science for decades."),
(1351,"channel","n./v.","/'tSAn@l/","频道；★渠道；引导","We need to channel more resources into research."),
(1352,"chaos","n.","/'keIA:s/","混乱","The CEO's resignation threw the company into chaos."),
(1353,"character","n.","/'kAr@kt@r/","性格；★角色；★字符","Honesty is an essential part of his character."),
(1354,"characteristic","adj./n.","/kAr@kt@'rIstIk/","特有的；特征","Generosity is a family characteristic."),
(1355,"characterize","v.","/'kAr@kt@raIz/","以…为特征","The region is characterized by its mild climate."),
(1356,"charity","n.","/'tSAr@ti/","慈善；慈善机构","All profits go to charity."),
(1357,"charm","n./v.","/tSA:rm/","魅力；吸引","The village has a unique charm that attracts tourists."),
(1358,"chart","n./v.","/tSA:rt/","图表；绘制图表","The report includes charts illustrating the results."),
(1359,"charter","n./v.","/'tSA:rt@r/","宪章；特许","The organization operates under a government charter."),
(1360,"chase","v./n.","/tSeIs/","追逐；追求","Police chased the suspect through the streets."),
(1361,"chemical","adj./n.","/'kemIk@l/","化学的；化学品","The factory was fined for dumping toxic chemicals."),
(1362,"cherish","v.","/'tSerIS/","珍视；★怀有","I will always cherish our time together."),
(1363,"chief","adj./n.","/tSi:f/","主要的；首领","The chief reason was a shortage of materials."),
(1364,"chip","n./v.","/tSIp/","芯片；★碎片；★削","The company invests billions in next-gen chips."),
(1365,"chronic","adj.","/'krA:nIk/","慢性的；长期的","The city has a chronic shortage of housing."),
(1366,"circuit","n.","/'s3:rkIt/","电路；★巡回","The lecture circuit took her across the country."),
(1367,"circulate","v.","/'s3:rkj@leIt/","循环；★传播","Rumors about the merger began to circulate."),
(1368,"circumstance","n.","/'s3:rk@mstAns/","情况；环境","Under no circumstances reveal your password."),
(1369,"cite","v.","/saIt/","引用；★传唤","The author cites over 200 sources."),
(1370,"citizen","n.","/'sItIz@n/","公民","All citizens have the right to vote."),
(1371,"civil","adj.","/'sIv@l/","公民的；★民事的；★文明的","The dispute was resolved through civil litigation."),
(1372,"civilian","n./adj.","/sI'vIlj@n/","平民；民用的","The bombing caused heavy civilian casualties."),
(1373,"civilization","n.","/sIv@laI'zeIS@n/","文明","Ancient Egyptian civilization flourished along the Nile."),
(1374,"claim","v./n.","/kleIm/","声称；★索赔","The insurance company rejected his claim."),
(1375,"clarify","v.","/'klArIfaI/","澄清；阐明","Could you clarify what you meant?"),
(1376,"clash","n./v.","/klAS/","冲突；冲突","The demonstration ended in violent clashes with police."),
(1377,"classic","adj./n.","/'klAsIk/","经典的；名著","The novel is a classic of 20th-century literature."),
(1378,"classify","v.","/'klAsIfaI/","分类","Documents are classified by confidentiality level."),
(1379,"clause","n.","/klO:z/","从句；★条款","The contract contains a confidentiality clause."),
(1380,"clergy","n.","/'kl3:rdZi/","神职人员","The clergy mediated the conflict between communities."),
]

lines = []
lines.append(f"## Big Day 8（词汇 1202-1380）")
lines.append("")
lines.append("| # | 单词 | 词性 | 音标 | 释义（★=熟词生义） | 例句 |")
lines.append("|---|------|------|------|-------------------|------|")
for num, word, pos, phon, defin, example in bd8:
    lines.append(f"| {num} | **{word}** | {pos} | {phon} | {defin} | {example} |")
lines.append("")

bak_path = r"C:\Users\方向容\Documents\408学习\408-学习管理\英语\考研词汇_词库.md"
with open(bak_path, "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"OK: appended Big Day 8 ({len(bd8)} words)")
