# -*- coding: utf-8 -*-
import sys; sys.stdout.reconfigure(encoding='utf-8')

bd9 = [
(1381,"climate","n.","/'klaIm@t/","气候；★氛围","The political climate has become increasingly polarized."),
(1382,"cling","v.","/klIN/","紧紧抓住；★坚持","She clung to the hope her son would one day return."),
(1383,"clinic","n.","/'klInIk/","诊所","The free clinic provides healthcare to uninsured patients."),
(1384,"clip","n./v.","/klIp/","夹子；★剪","She clipped the article from the newspaper."),
(1385,"clockwise","adv./adj.","/'klA:kwaIz/","顺时针方向的","Turn the knob clockwise to increase the volume."),
(1386,"clone","n./v.","/kloun/","克隆；克隆","The technology to clone humans is highly controversial."),
(1387,"clue","n.","/klu:/","线索","The detective found a crucial clue at the crime scene."),
(1388,"clumsy","adj.","/'kl^mzi/","笨拙的","His clumsy attempt to apologize made things worse."),
(1389,"cluster","n./v.","/'kl^st@r/","群；聚集","The city has a cluster of high-tech companies near the university."),
(1390,"coalition","n.","/kou@'lIS@n/","联盟","A coalition of environmental groups called for urgent action."),
(1391,"coarse","adj.","/kO:rs/","粗糙的；★粗鲁的","The fabric was too coarse for a baby's sensitive skin."),
(1392,"code","n./v.","/koud/","密码；★准则；编码","All students must adhere to the school's code of conduct."),
(1393,"cognitive","adj.","/'kA:gn@tIv/","认知的","The study examines cognitive development in early childhood."),
(1394,"coherent","adj.","/kou'hIr@nt/","连贯的；一致的","She gave a coherent account of what happened."),
(1395,"coincide","v.","/kouIn'saId/","同时发生；★一致","His interests coincide with those of the organization."),
(1396,"coincidence","n.","/kou'InsId@ns/","巧合","It was sheer coincidence we were on the same flight."),
(1397,"collaborate","v.","/k@'lAb@reIt/","合作；★通敌","The two universities collaborate on joint research."),
(1398,"collapse","v./n.","/k@'lAps/","倒塌；崩溃","The bridge collapsed under the weight of the truck."),
(1399,"colleague","n.","/'kA:li:g/","同事","I discussed the proposal with several colleagues."),
(1400,"collective","adj./n.","/k@'lektIv/","集体的；集体","The decision was the result of collective deliberation."),
(1401,"collision","n.","/k@'lIZ@n/","碰撞；冲突","The train collision resulted in over 50 injuries."),
(1402,"colonial","adj.","/k@'louni@l/","殖民地的","The country gained independence after decades of colonial rule."),
(1403,"colony","n.","/'kA:l@ni/","殖民地","Australia was originally a British penal colony."),
(1404,"combat","n./v.","/'kA:mbAt/","战斗；与…斗争","The government launched a new initiative to combat unemployment."),
(1405,"combine","v.","/k@m'baIn/","结合","The new drug combines three active ingredients."),
(1406,"comedy","n.","/'kA:m@di/","喜剧","The film is a romantic comedy set in modern New York."),
(1407,"command","v./n.","/k@'mAnd/","命令；★掌握；命令","She commands a salary of over $200,000 per year."),
(1408,"commemorate","v.","/k@'mem@reIt/","纪念","A statue was erected to commemorate the fallen soldiers."),
(1409,"commence","v.","/k@'mens/","开始","The trial is scheduled to commence next Monday."),
(1410,"commend","v.","/k@'mend/","赞扬","The firefighters were commended for their bravery."),
(1411,"comment","n./v.","/'kA:ment/","评论；评论","The CEO declined to comment on the rumors."),
(1412,"commerce","n.","/'kA:m3:rs/","商业；贸易","E-commerce has revolutionized the way people shop."),
(1413,"commission","n./v.","/k@'mIS@n/","委员会；★佣金；委托","The artist was commissioned to paint a portrait."),
(1414,"commit","v.","/k@'mIt/","犯；★承诺","The government committed to reducing carbon emissions by 40%."),
(1415,"commodity","n.","/k@'mA:d@ti/","商品","Oil is one of the world's most actively traded commodities."),
(1416,"commonplace","adj./n.","/'kA:m@npleIs/","平凡的；常见的事","Smartphones have become commonplace even in poor regions."),
(1417,"communal","adj.","/k@'mju:n@l/","公共的；社区的","The apartment has a communal garden on the rooftop."),
(1418,"communicate","v.","/k@'mju:nIkeIt/","交流；★传达","The ability to communicate clearly is essential at work."),
(1419,"community","n.","/k@'mju:n@ti/","社区；★群体","The international community must work together on climate change."),
(1420,"commute","v./n.","/k@'mju:t/","通勤；★减刑","He commutes two hours each day from the suburbs."),
(1421,"compact","adj./v.","/'kA:mpAkt/","紧凑的；压缩","The apartment is compact but cleverly designed."),
(1422,"companion","n.","/k@m'pAnj@n/","同伴","A dog can be a loyal companion for many years."),
(1423,"comparable","adj.","/'kA:mp@r@b@l/","可比较的","The quality is comparable to much more expensive brands."),
(1424,"comparative","adj.","/k@m'pAr@tIv/","比较的；相对的","She is a comparative newcomer to neuroscience."),
(1425,"comparison","n.","/k@m'pArIs@n/","比较","In comparison with last year, profits increased by 25%."),
(1426,"compartment","n.","/k@m'pA:rtm@nt/","隔间","He stored his luggage in the overhead compartment."),
(1427,"compassion","n.","/k@m'pAS@n/","同情","The nurse showed great compassion for suffering patients."),
(1428,"compatible","adj.","/k@m'pAt@b@l/","兼容的；一致的","The software is compatible with both Windows and Mac."),
(1429,"compel","v.","/k@m'pel/","强迫","The evidence compelled the jury to return a guilty verdict."),
(1430,"compensate","v.","/'kA:mp@nseIt/","补偿","The company agreed to compensate affected customers."),
(1431,"compete","v.","/k@m'pi:t/","竞争","Small businesses struggle to compete with multinationals."),
(1432,"competence","n.","/'kA:mp@t@ns/","能力","She demonstrated exceptional competence in handling the crisis."),
(1433,"compile","v.","/k@m'paIl/","编纂","The report was compiled from five years of data."),
(1434,"complement","v./n.","/'kA:mplIment/","补充；补充物","The two musicians complement each other perfectly."),
(1435,"complex","adj./n.","/'kA:mpleks/","复杂的；复合体","The issue is far more complex than most people realize."),
(1436,"complicate","v.","/'kA:mplIkeIt/","使复杂化","His refusal further complicated an already difficult situation."),
(1437,"compliment","n./v.","/'kA:mplIm@nt/","赞美；称赞","The chef received many compliments on the meal."),
(1438,"comply","v.","/k@m'plaI/","遵守","All companies must comply with data protection regulations."),
(1439,"component","n.","/k@m'poun@nt/","成分；部件","Trust is a vital component of any healthy relationship."),
(1440,"compose","v.","/k@m'pouz/","组成；★创作","The committee is composed of experts from various fields."),
(1441,"compound","n./adj./v.","/'kA:mpaund/","化合物；使复合","The problem is compounded by a lack of funding."),
(1442,"comprehend","v.","/kA:mprI'hend/","理解","The magnitude of the disaster is difficult to comprehend."),
(1443,"comprehensive","adj.","/kA:mprI'hensIv/","全面的","The report offers a comprehensive analysis of the economy."),
(1444,"compress","v.","/k@m'pres/","压缩","The file was compressed for easier email attachment."),
(1445,"comprise","v.","/k@m'praIz/","包括；构成","Women comprise over half of the service sector workforce."),
(1446,"compromise","n./v.","/'kA:mpr@maIz/","妥协；损害","Neither side was willing to compromise on the core issue."),
(1447,"compulsory","adj.","/k@m'p^ls@ri/","强制性的","Education is compulsory for children aged 5 to 16."),
(1448,"compute","v.","/k@m'pju:t/","计算","The algorithm computes the optimal route in under a second."),
(1449,"conceal","v.","/k@n'si:l/","隐藏","She tried to conceal her disappointment behind a smile."),
(1450,"concede","v.","/k@n'si:d/","承认；★让步","The government finally conceded the policy had failed."),
(1451,"conceive","v.","/k@n'si:v/","构想；★怀孕","It is difficult to conceive of a world without the internet."),
(1452,"concentrate","v.","/'kA:ns@ntreIt/","集中；专注","I find it hard to concentrate with loud music playing."),
(1453,"concept","n.","/'kA:nsept/","概念","Sustainability is central to modern environmental policy."),
(1454,"conception","n.","/k@n'sepS@n/","概念；★怀孕","The book challenges traditional conceptions of gender."),
(1455,"concise","adj.","/k@n'saIs/","简洁的","Please keep your answers concise and to the point."),
(1456,"conclude","v.","/k@n'klu:d/","得出结论；★结束","The meeting concluded with a vote on the proposal."),
(1457,"concrete","adj./n.","/'kA:Nkri:t/","具体的；混凝土","We need concrete evidence, not just speculation."),
(1458,"condemn","v.","/k@n'dem/","谴责","The UN resolution condemned the use of chemical weapons."),
(1459,"condense","v.","/k@n'dens/","浓缩；压缩","The article was condensed from a 50-page report."),
(1460,"confer","v.","/k@n'f3:r/","授予；★商议","The president conferred with his advisors before the announcement."),
(1461,"confess","v.","/k@n'fes/","坦白；承认","He confessed to the crime after hours of questioning."),
(1462,"configuration","n.","/k@n/fIgj@'reIS@n/","配置；布局","The software can be customized in many configurations."),
(1463,"confront","v.","/k@n'fr^nt/","面对；对抗","The government must confront growing income inequality."),
(1464,"congress","n.","/'kA:Ngr@s/","国会；代表大会","The bill was passed by Congress with bipartisan support."),
(1465,"conjunction","n.","/k@n'dZ^NkS@n/","连接；★连词","The drug should not be used in conjunction with alcohol."),
(1466,"conquer","v.","/'kA:Nk@r/","征服；★克服","She finally conquered her fear of public speaking."),
(1467,"conscience","n.","/'kA:nS@ns/","良心","He could not in good conscience sign a false document."),
(1468,"conscientious","adj.","/kA:nSi'enS@s/","认真负责的","She is a conscientious worker who never misses deadlines."),
(1469,"consensus","n.","/k@n'sens@s/","共识","There is broad consensus that the climate is changing."),
(1470,"consent","n./v.","/k@n'sent/","同意；同意","No procedure can be performed without the patient's consent."),
(1471,"consequently","adv.","/'kA:ns@kwentli/","因此","The company lost its biggest client; consequently, profits fell."),
(1472,"conservation","n.","/kA:ns@r'veIS@n/","保护；保存","The organization is dedicated to conservation of endangered species."),
(1473,"considerable","adj.","/k@n'sId@r@b@l/","相当大的","The project attracted considerable interest from investors."),
(1474,"considerate","adj.","/k@n'sId@r@t/","体贴的","It was considerate of you to offer to drive her home."),
(1475,"consist","v.","/k@n'sIst/","由…组成(consist of)","The course consists of 12 lectures and four practical sessions."),
(1476,"consolidate","v.","/k@n'sA:lIdeIt/","巩固；合并","The merger will consolidate the company's market position."),
(1477,"conspicuous","adj.","/k@n'spIkju@s/","显眼的","The statue is the most conspicuous landmark in the square."),
(1478,"constant","adj.","/'kA:nst@nt/","不断的","The baby requires constant attention and care."),
(1479,"constituent","n./adj.","/k@n'stItSu@nt/","成分；★选民","The senator listened to the concerns of her constituents."),
(1480,"constitute","v.","/'kA:nstItu:t/","构成","The new evidence constitutes grounds for a retrial."),
(1481,"constitution","n.","/kA:nstI'tu:S@n/","宪法；★体质","The constitution guarantees freedom of speech."),
(1482,"constrain","v.","/k@n'streIn/","限制；约束","The company is constrained by a lack of financial resources."),
(1483,"construct","n.","/'kA:nstr^kt/","概念；构想","Race is a social construct rather than a biological reality."),
(1484,"consult","v.","/k@n's^lt/","咨询；查阅","You should consult a lawyer before signing any legal documents."),
(1485,"consume","v.","/k@n'su:m/","消耗","The country consumes more oil than any other nation."),
(1486,"contact","n./v.","/'kA:ntAkt/","接触；联系","Scientists made contact with a remote tribe in the Amazon."),
(1487,"contaminate","v.","/k@n'tAmIneIt/","污染","The water supply was contaminated by factory chemicals."),
(1488,"contemplate","v.","/'kA:nt@mpleIt/","沉思；★考虑","He is contemplating a complete career change."),
(1489,"contemporary","adj.","/k@n'temp@reri/","当代的","The gallery exhibits works by contemporary artists."),
(1490,"contempt","n.","/k@n'tempt/","蔑视","His behavior showed a complete contempt for the rules."),
(1491,"contend","v.","/k@n'tend/","主张；★竞争","The two athletes will contend for the gold medal."),
(1492,"context","n.","/'kA:ntekst/","背景；上下文","Historical context is essential for understanding this novel."),
(1493,"continent","n.","/'kA:ntIn@nt/","大陆","Africa is the second largest continent on Earth."),
(1494,"contract","v.","/k@n'trAkt/","收缩","Metals contract when they cool down."),
(1495,"contradict","v.","/kA:ntr@'dIkt/","反驳；与…矛盾","His later statement directly contradicts his earlier one."),
(1496,"contrast","n./v.","/'kA:ntrAst/","对比；对比","In contrast to his outgoing sister, he is quite shy."),
(1497,"contribute","v.","/k@n'trIbju:t/","贡献","Exercise contributes significantly to overall health."),
(1498,"contrive","v.","/k@n'traIv/","设法做到；★谋划","She contrived to get tickets for the sold-out concert."),
(1499,"controversy","n.","/'kA:ntr@v3:rsi/","争议","The proposal has sparked fierce controversy among residents."),
(1500,"convene","v.","/k@n'vi:n/","召集","The committee will convene next week to discuss the budget."),
(1501,"convenient","adj.","/k@n'vi:ni@nt/","方便的","The hotel is conveniently located near the station."),
(1502,"convention","n.","/k@n'venS@n/","大会","The annual convention attracts over 10,000 attendees."),
(1503,"converge","v.","/k@n'v3:rdZ/","汇聚","Thousands of protesters converged on the city center."),
(1504,"conversely","adv.","/'kA:nv3:rsli/","相反地","The rich get richer; conversely, the poor get poorer."),
(1505,"convert","v.","/k@n'v3:rt/","转变","The old warehouse was converted into an art gallery."),
(1506,"convey","v.","/k@n'veI/","传达","The poet conveys a deep sense of longing in just a few lines."),
(1507,"convict","v./n.","/k@n'vIkt/","定罪；罪犯","He was convicted of fraud and sentenced to five years."),
(1508,"conviction","n.","/k@n'vIkS@n/","信念；★定罪","She spoke with great conviction about the need for reform."),
(1509,"coordinate","n.","/kou'O:rdIn@t/","坐标","The pilot checked the coordinates before beginning the descent."),
(1510,"cope","v.","/koup/","应对；处理","The hospital is struggling to cope with the influx of patients."),
(1511,"copyright","n.","/'kA:pi/raIt/","版权","The song is protected by copyright law."),
(1512,"cord","n.","/kO:rd/","绳索","He tied the package with a length of nylon cord."),
(1513,"core","n./adj.","/kO:r/","核心；核心的","The core issue is not money but a lack of trust."),
(1514,"cornerstone","n.","/'kO:rn@rstoun/","基石","Education is the cornerstone of a prosperous society."),
(1515,"corporate","adj.","/'kO:rp@r@t/","公司的","The company has a strong corporate culture of innovation."),
(1516,"correlate","v.","/'kO:r@leIt/","相关联","Stress levels are closely correlated with job satisfaction."),
(1517,"correspond","v.","/kO:r@'spA:nd/","对应","The numbers on the map correspond to the list below."),
(1518,"correspondent","n.","/kO:r@'spA:nd@nt/","记者","She works as a foreign correspondent for a major network."),
(1519,"corrode","v.","/k@'roud/","腐蚀","The metal pipes had been badly corroded by acidic water."),
(1520,"corrupt","adj./v.","/k@'r^pt/","腐败的；使腐败","Power corrupts those who wield it without accountability."),
(1521,"cosmic","adj.","/'kA:zmIk/","宇宙的","The telescope detects cosmic radiation from distant galaxies."),
(1522,"costly","adj.","/'kO:stli/","昂贵的","The delay proved extremely costly for the company."),
(1523,"council","n.","/'kauns@l/","委员会","The city council voted unanimously to approve the new park."),
(1524,"counsel","n.","/'kauns@l/","建议","The defendant was represented by legal counsel throughout the trial."),
(1525,"counterpart","n.","/'kaunt@rpA:rt/","对应的人或物","The US Secretary met with his Chinese counterpart in Beijing."),
(1526,"coupon","n.","/'ku:pA:n/","优惠券","Use this coupon to get 20% off your next purchase."),
(1527,"courage","n.","/'k3:rIdZ/","勇气","It takes great courage to stand up for what you believe."),
(1528,"course","n.","/kO:rs/","课程","She enrolled in a course on artificial intelligence."),
(1529,"courtesy","n.","/'k3:rt@si/","礼貌","As a courtesy, please turn off your phone during the performance."),
(1530,"coverage","n.","/'k^v@rIdZ/","覆盖范围","The insurance policy provides coverage for accidental damage."),
(1531,"crack","n./v.","/krAk/","裂缝；破裂","A crack appeared in the wall after the earthquake."),
(1532,"cradle","n.","/'kreId@l/","摇篮","The region is called the cradle of Western civilization."),
(1533,"craft","v.","/krAft/","精心制作","Each piece of furniture is individually crafted by artisans."),
(1534,"crash","n./v.","/krAS/","撞车；碰撞","The stock market crash of 1929 triggered the Great Depression."),
(1535,"credential","n.","/kr@'denS@l/","资历；证书","She has excellent academic credentials from a top university."),
(1536,"credit","n./v.","/'kredIt/","信用；★归功于","The discovery is credited to a team in Japan."),
(1537,"crew","n.","/kru:/","全体船员","The crew worked tirelessly to keep the ship afloat."),
(1538,"criminal","adj./n.","/'krImIn@l/","犯罪的；罪犯","The criminal justice system needs comprehensive reform."),
(1539,"cripple","v./n.","/'krIp@l/","严重削弱；残疾人","The strike crippled the country's transportation network."),
(1540,"criterion","n.","/kraI'tIri@n/","标准","The main criterion for selection is academic performance."),
(1541,"critic","n.","/'krItIk/","评论家；批评者","The film received rave reviews from critics nationwide."),
(1542,"critical","adj.","/'krItIk@l/","批评的","She is highly critical of the government's handling of the crisis."),
(1543,"criticize","v.","/'krItIsaIz/","批评","The report was widely criticized for its lack of rigor."),
(1544,"crucial","adj.","/'kru:S@l/","至关重要的","The next few months will be crucial for the company."),
(1545,"crude","adj.","/kru:d/","粗糙的；★天然的","Crude oil prices have fallen to a decade low."),
(1546,"crush","v./n.","/kr^S/","压碎；迷恋","The rebellion was brutally crushed by government forces."),
(1547,"crystal","n.","/'krIst@l/","水晶；晶体","The chandelier is made of the finest Austrian crystal."),
(1548,"cue","n.","/kju:/","提示；暗示","She took his silence as a cue to change the subject."),
(1549,"cultivate","v.","/'k^ltIveIt/","培养","The company has carefully cultivated an image of reliability."),
(1550,"cunning","adj./n.","/'k^nIN/","狡猾的；狡猾","The fox is known for its cunning in escaping hunters."),
(1551,"curb","v./n.","/k3:rb/","控制；路缘","The government introduced measures to curb inflation."),
(1552,"curiosity","n.","/kjUri'A:s@ti/","好奇心","Curiosity drives scientific discovery."),
(1553,"currency","n.","/'k3:r@nsi/","货币","The euro is the official currency of 19 European countries."),
(1554,"curriculum","n.","/k@'rIkj@l@m/","课程","The curriculum has been updated to include more practical training."),
(1555,"curve","n./v.","/k3:rv/","曲线；弯曲","The road curves sharply just before the village."),
(1556,"cushion","n./v.","/'kUS@n/","垫子；缓冲","Her savings provided a cushion against unexpected expenses."),
(1557,"custom","n.","/'k^st@m/","习俗","It is the custom to remove shoes before entering a home."),
(1558,"cynical","adj.","/'sInIk@l/","愤世嫉俗的","She was cynical about politicians promising to lower taxes."),
(1559,"dairy","n.","/'deri/","乳制品","The company is one of the largest dairy producers in the country."),
(1560,"dam","n./v.","/dAm/","水坝；筑坝","The massive dam generates electricity for over 10 million homes."),
]

lines = []
lines.append(f"## Big Day 9（词汇 1381-1560）")
lines.append("")
lines.append("| # | 单词 | 词性 | 音标 | 释义（★=熟词生义） | 例句 |")
lines.append("|---|------|------|------|-------------------|------|")
for num, word, pos, phon, defin, example in bd9:
    lines.append(f"| {num} | **{word}** | {pos} | {phon} | {defin} | {example} |")
lines.append("")

bak_path = r"C:\Users\方向容\Documents\408学习\408-学习管理\英语\考研词汇_词库.md"
with open(bak_path, "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"OK: appended Big Day 9 ({len(bd9)} words)")
