# -*- coding: utf-8 -*-
"""Batch-generate remaining big days with concise examples for speed."""
import sys; sys.stdout.reconfigure(encoding='utf-8')

# Compact word data: (num, word, pos, phon, defin, example)
# BD10: 1561-1740
bd10 = [
(1561,"damp","adj./n.","/dAmp/","潮湿的；潮湿","The basement felt cold and damp after the rain."),
(1562,"dazzle","v.","/'dAz@l/","使眩目；★使惊叹","The young pianist dazzled the audience with her performance."),
(1563,"deadline","n.","/'dedlaIn/","截止日期","The deadline for applications is next Friday."),
(1564,"deadly","adj.","/'dedli/","致命的","The disease is potentially deadly if not treated early."),
(1565,"dean","n.","/di:n/","院长","The dean of the medical school announced his retirement."),
(1566,"debris","n.","/d@'bri:/","碎片；残骸","Rescue workers searched through debris for survivors."),
(1567,"debt","n.","/det/","债务","The country struggles under massive foreign debt."),
(1568,"deceive","v.","/dI'si:v/","欺骗","He was deceived into signing a contract he did not understand."),
(1569,"decent","adj.","/'di:s@nt/","体面的；得体的","Everyone deserves a decent standard of living."),
(1570,"decisive","adj.","/dI'saIsIv/","决定性的；果断的","A decisive victory changed the course of the war."),
(1571,"declaration","n.","/dekl@'reIS@n/","宣言；声明","The Declaration of Independence was signed in 1776."),
(1572,"decorate","v.","/'dek@reIt/","装饰","We spent the afternoon decorating the room for the party."),
(1573,"dedicate","v.","/'dedIkeIt/","奉献","She dedicated her life to fighting for social justice."),
(1574,"deduce","v.","/dI'du:s/","推断","Detectives deduced the fire was deliberate."),
(1575,"deem","v.","/di:m/","认为","The proposal was deemed unacceptable by the committee."),
(1576,"defect","n./v.","/'di:fekt/","缺陷；叛逃","The product was recalled due to a manufacturing defect."),
(1577,"deficiency","n.","/dI'fIS@nsi/","缺乏；缺陷","Vitamin D deficiency is common in northern countries."),
(1578,"deficit","n.","/'defIsIt/","赤字；不足","The government runs a budget deficit of over $1 trillion."),
(1579,"delegate","n./v.","/'delIg@t/","代表；委派","Learn to delegate tasks effectively as a manager."),
(1580,"delete","v.","/dI'li:t/","删除","Delete unnecessary files to free up disk space."),
(1581,"deliberately","adv.","/dI'lIb@r@tli/","故意地","She deliberately ignored his messages for a week."),
(1582,"delicate","adj.","/'delIk@t/","精致的","The negotiations are at a very delicate stage."),
(1583,"delivery","n.","/dI'lIv@ri/","递送","The restaurant offers free delivery for orders over $30."),
(1584,"democracy","n.","/dI'mA:kr@si/","民主","Democracy requires an informed and engaged citizenry."),
(1585,"demographic","adj./n.","/dem@'grAfIk/","人口统计的；人口群体","The campaign targets the 18-35 demographic."),
(1586,"demonstrate","v.","/'dem@nstreIt/","展示","The experiment demonstrates that light travels faster than sound."),
(1587,"denial","n.","/dI'naI@l/","否认","His denial of involvement was met with skepticism."),
(1588,"denote","v.","/dI'nout/","表示","The symbol pi denotes the ratio of circumference to diameter."),
(1589,"dense","adj.","/dens/","稠密的","The city has one of the densest populations in the world."),
(1590,"depict","v.","/dI'pIkt/","描绘","The film depicts life in a small Chinese village."),
(1591,"deploy","v.","/dI'plOI/","部署","Troops were deployed to the border amid rising tensions."),
(1592,"depreciate","v.","/dI'pri:SieIt/","贬值","New cars depreciate rapidly in their first year."),
(1593,"depress","v.","/dI'pres/","使沮丧","The constant rain depressed everyone's mood."),
(1594,"deprive","v.","/dI'praIv/","剥夺","No child should be deprived of access to education."),
(1595,"descend","v.","/dI'send/","下降","The plane began to descend as it approached the airport."),
(1596,"designate","v.","/'dezIgneIt/","指定","The area has been designated as a national park since 1950."),
(1597,"despair","n./v.","/dI'sper/","绝望；绝望","He fell into despair after losing his job and home."),
(1598,"destination","n.","/destI'neIS@n/","目的地","Paris is one of the most popular tourist destinations."),
(1599,"destiny","n.","/'dest@ni/","命运","She believes destiny brought them together."),
(1600,"destruction","n.","/dI'str^kS@n/","破坏","The hurricane caused widespread destruction along the coast."),
(1601,"detach","v.","/dI'tAtS/","分开","You can detach the keyboard from the tablet."),
(1602,"detain","v.","/dI'teIn/","拘留","Several suspects were detained for questioning by police."),
(1603,"detect","v.","/dI'tekt/","检测","The device can detect even the slightest vibration."),
(1604,"deteriorate","v.","/dI'tIri@reIt/","恶化","The patient's condition deteriorated rapidly overnight."),
(1605,"determine","v.","/dI't3:rmIn/","决定","A thorough investigation will determine the cause."),
(1606,"devastate","v.","/'dev@steIt/","摧毁","The war devastated the country's economy and infrastructure."),
(1607,"device","n.","/dI'vaIs/","装置","The new device can translate speech in real time."),
(1608,"devise","v.","/dI'vaIz/","设计；发明","The team devised a clever solution to the problem."),
(1609,"diagnose","v.","/daI@gnous/","诊断","The disease was diagnosed too late for effective treatment."),
(1610,"diagram","n.","/'daI@grAm/","图表","The teacher used a diagram to explain the heart's structure."),
(1611,"dialect","n.","/'daI@lekt/","方言","The local dialect is quite different from standard Mandarin."),
(1612,"diameter","n.","/daI'Am@t@r/","直径","The pipe has a diameter of approximately 15 centimeters."),
(1613,"dictate","v.","/'dIkteIt/","口述；★支配","Market conditions dictate that we must cut costs."),
(1614,"differ","v.","/'dIf@r/","不同","Opinions differ widely on the best approach."),
(1615,"differentiate","v.","/dIf@'renSieIt/","区分","It is important to differentiate facts from opinions."),
(1616,"digest","v./n.","/daI'dZest/","消化；摘要","It takes time to digest complex information."),
(1617,"digital","adj.","/'dIdZIt@l/","数字的","The shift to digital payments has accelerated recently."),
(1618,"dignity","n.","/'dIgn@ti/","尊严","Every human deserves to be treated with dignity and respect."),
(1619,"dilemma","n.","/dI'lem@/","困境","The prime minister faces a difficult dilemma over the policy."),
(1620,"diligent","adj.","/'dIlIdZ@nt/","勤奋的","She is a diligent student who always submits work on time."),
(1621,"dilute","v.","/daI'lu:t/","稀释","The company was accused of diluting its products to cut costs."),
(1622,"dimension","n.","/dI'menS@n/","维度；★方面","The social dimension of urban planning is often overlooked."),
(1623,"diploma","n.","/dI'ploum@/","文凭","She received her diploma at the graduation ceremony."),
(1624,"diplomatic","adj.","/dIpl@'mAtIk/","外交的","A diplomatic solution remains the preferred option."),
(1625,"directory","n.","/dI'rekt@ri/","目录","The telephone directory lists all local businesses."),
(1626,"disable","v.","/dIs'eIb@l/","使丧失能力","The accident disabled him for life."),
(1627,"disastrous","adj.","/dI'zAstr@s/","灾难性的","The decision proved disastrous for the company's reputation."),
(1628,"discard","v.","/dIs'kA:rd/","丢弃","Old electronics should not be discarded with household waste."),
(1629,"discern","v.","/dI's3:rn/","辨别","It is difficult to discern any real difference between them."),
(1630,"discharge","v./n.","/dIs'tSA:rdZ/","排放；★解雇","The factory was fined for discharging toxic waste."),
(1631,"disclose","v.","/dIs'klouz/","披露","The company was forced to disclose its financial records."),
(1632,"discourse","n./v.","/'dIskO:rs/","话语；论述","The professor delivered a discourse on democracy."),
(1633,"discreet","adj.","/dI'skri:t/","谨慎的","She was discreet about her personal life."),
(1634,"discrepancy","n.","/dI'skrep@nsi/","差异；不一致","Investigators found a discrepancy in his statement."),
(1635,"disguise","v./n.","/dIs'gaIz/","伪装；伪装","He disguised himself as a janitor to enter the building."),
(1636,"disgust","n./v.","/dIs'g^st/","厌恶；使厌恶","The idea of eating raw meat disgusts many people."),
(1637,"dismantle","v.","/dIs'mAnt@l/","拆除","The old power plant is being dismantled piece by piece."),
(1638,"dismay","n./v.","/dIs'meI/","沮丧；使沮丧","To her dismay, she found her passport had expired."),
(1639,"dismiss","v.","/dIs'mIs/","解雇；★不考虑","The judge dismissed the case due to lack of evidence."),
(1640,"dispatch","v./n.","/dI'spAtS/","派遣；急件","An ambulance was dispatched to the scene within minutes."),
(1641,"disperse","v.","/dI'sp3:rs/","分散","The crowd dispersed peacefully after the concert ended."),
(1642,"displace","v.","/dIs'pleIs/","取代；★使流离失所","Thousands of families were displaced by the flooding."),
(1643,"disposal","n.","/dI'spouz@l/","处理","The city provides facilities for safe disposal of hazardous waste."),
(1644,"disrupt","v.","/dIs'r^pt/","扰乱","The strike disrupted train services across the entire region."),
(1645,"dissolve","v.","/dI'zA:lv/","溶解","Sugar dissolves more quickly in hot water than in cold."),
(1646,"distil","v.","/dI'stIl/","蒸馏；★提炼","The book distills decades of research into one volume."),
(1647,"distort","v.","/dI'stO:rt/","扭曲","The media sometimes distorts the truth for more viewers."),
(1648,"distract","v.","/dI'strAkt/","使分心","The noise from outside distracted her from her work."),
(1649,"distress","n./v.","/dI'stres/","痛苦；使痛苦","The news caused great distress to the families."),
(1650,"disturb","v.","/dI'st3:rb/","打扰","Please do not disturb the animals in their natural habitat."),
(1651,"dive","v./n.","/daIv/","跳水；潜水","Sales took a dive after the negative reviews were published."),
(1652,"diverse","adj.","/daI'v3:rs/","多样的","The university has a diverse student body."),
(1653,"diversion","n.","/daI'v3:rZ@n/","转移；★娱乐","The film provides light diversion after a long week."),
(1654,"dividend","n.","/'dIvIdend/","股息","The company paid a generous dividend to shareholders."),
(1655,"divine","adj.","/dI'vaIn/","神圣的","Ancient cultures believed kings had a divine right to rule."),
(1656,"doctrine","n.","/'dA:ktrIn/","教义；学说","Separation of powers is fundamental to modern democracy."),
(1657,"domain","n.","/d@'meIn/","领域","The research falls within the domain of molecular biology."),
(1658,"domestic","adj.","/d@'mestIk/","国内的","Domestic flights are often cheaper than international ones."),
(1659,"dominant","adj.","/'dA:mIn@nt/","主导的","The company has a dominant position in the smartphone market."),
(1660,"donate","v.","/'douneIt/","捐赠","She donated a large sum to the children's hospital."),
(1661,"doom","n./v.","/du:m/","厄运；注定","The project was doomed from the start due to lack of funding."),
(1662,"dose","n.","/dous/","剂量","The recommended dose is two tablets twice daily."),
(1663,"draft","n.","/drAft/","草稿","She is working on the first draft of her dissertation."),
(1664,"drag","v.","/drAg/","拖","The negotiations dragged on for months without progress."),
(1665,"drain","v./n.","/dreIn/","排水；消耗","The long commute was a constant drain on his energy."),
(1666,"drama","n.","/'drA:m@/","戏剧","The political drama dominated the news headlines."),
(1667,"drastic","adj.","/'drAstIk/","激烈的","The government took drastic measures to control the virus."),
(1668,"dread","v./n.","/dred/","恐惧；恐惧","She dreaded the thought of speaking in front of a large audience."),
(1669,"drift","v./n.","/drIft/","漂流；趋势","The conversation drifted from politics to personal matters."),
(1670,"drought","n.","/draut/","干旱","The severe drought has devastated crops across the region."),
(1671,"dual","adj.","/'du:@l/","双重的","She holds dual citizenship in Canada and the UK."),
(1672,"dubious","adj.","/'du:bi@s/","可疑的","The company's accounting practices are highly dubious."),
(1673,"dump","v./n.","/d^mp/","倾倒；垃圾场","The factory was caught illegally dumping waste into the river."),
(1674,"duplicate","v./n.","/'du:plIk@t/","复制；副本","Please make a duplicate of this key before you hand it back."),
(1675,"durable","adj.","/'dUr@b@l/","耐用的","The furniture is made of durable hardwood that will last for generations."),
(1676,"dwell","v.","/dwel/","居住；★详述(dwell on)","There is no point in dwelling on past mistakes."),
(1677,"dynasty","n.","/'daIn@sti/","王朝","The Ming dynasty ruled China for nearly three centuries."),
(1678,"ease","n./v.","/i:z/","容易；缓解","The medicine should help ease the pain within a few hours."),
(1679,"eccentric","adj.","/Ik'sentrIk/","古怪的","The eccentric professor was known for his unusual teaching methods."),
(1680,"eclipse","n./v.","/I'klIps/","日食；使黯然失色","Her performance eclipsed that of all other contestants."),
(1681,"ecology","n.","/i:'kA:l@dZi/","生态学","The study examines the ecology of tropical rainforests."),
(1682,"ecosystem","n.","/'i:kousIst@m/","生态系统","Coral reefs are among the most diverse ecosystems on the planet."),
(1683,"edge","n./v.","/edZ/","边缘；缓缓移动","The company is edging closer to bankruptcy each month."),
(1684,"edible","adj.","/'ed@b@l/","可食用的","Not all mushrooms are edible; some are highly poisonous."),
(1685,"efficiency","n.","/I'fIS@nsi/","效率","The new system has significantly improved our efficiency."),
(1686,"ego","n.","/'i:gou/","自我；自尊心","His enormous ego makes him difficult to work with."),
(1687,"elaborate","v.","/I'lAb@reIt/","详细阐述","Could you elaborate on the point you made earlier?"),
(1688,"elapse","v.","/I'lAps/","流逝","Three years had elapsed since they last saw each other."),
(1689,"elastic","adj.","/I'lAstIk/","有弹性的","Demand for luxury goods is highly elastic."),
(1690,"elbow","n./v.","/'elbou/","肘部；用肘推","She elbowed her way through the crowd to the front."),
(1691,"elderly","adj.","/'eld@rli/","年老的","The community center offers activities for elderly residents."),
(1692,"elect","v.","/I'lekt/","选举","She was elected chairperson by a wide margin."),
(1693,"elegant","adj.","/'el@g@nt/","优雅的","The solution is both elegant and surprisingly simple."),
(1694,"elevate","v.","/'elIveIt/","提升","He was elevated to the position of chief executive."),
(1695,"eligible","adj.","/'elIdZ@b@l/","有资格的","Only permanent residents are eligible to vote."),
(1696,"elite","n./adj.","/eI'li:t/","精英；精英的","The university attracts the academic elite from across the country."),
(1697,"eloquent","adj.","/'el@kw@nt/","雄辩的","She delivered an eloquent speech on the need for reform."),
(1698,"embark","v.","/Im'bA:rk/","着手(embark on)；乘船","The company is about to embark on its most ambitious project yet."),
(1699,"embarrass","v.","/Im'bAr@s/","使尴尬","His remark embarrassed everyone in the room."),
(1700,"embed","v.","/Im'bed/","嵌入","The journalist was embedded with the military unit during the conflict."),
(1701,"embody","v.","/Im'bA:di/","体现","The statue embodies the spirit of freedom and independence."),
(1702,"embrace","v.","/Im'breIs/","拥抱","The company has fully embraced digital transformation."),
(1703,"emerge","v.","/I'm3:rdZ/","出现","A clear pattern emerged from the analysis of the data."),
(1704,"eminent","adj.","/'emIn@nt/","杰出的","She is an eminent scholar in medieval history."),
(1705,"emit","v.","/I'mIt/","排放","The factory emits large quantities of carbon dioxide daily."),
(1706,"emotion","n.","/I'mouS@n/","情感","He struggled to control his emotions during the farewell speech."),
(1707,"empirical","adj.","/Im'pIrIk@l/","经验主义的","The theory is backed by extensive empirical research."),
(1708,"enclose","v.","/In'klouz/","围住；★附入","Please find enclosed a copy of my resume and cover letter."),
(1709,"encompass","v.","/In'k^mp@s/","包含","The course encompasses a wide range of computer science topics."),
(1710,"encounter","v.","/In'kaunt@r/","遇到","We encountered several unexpected challenges during the expedition."),
(1711,"endeavor","n.","/In'dev@r/","努力","Scientific endeavor requires both patience and creativity."),
(1712,"endorse","v.","/In'dO:rs/","支持；★背书","The proposal was endorsed by all members of the committee."),
(1713,"endow","v.","/In'dau/","赋予；★捐赠","She is endowed with a remarkable talent for music."),
(1714,"endure","v.","/In'dUr/","忍受","The refugees endured unimaginable hardships during their journey."),
(1715,"energetic","adj.","/en@r'dZetIk/","精力充沛的","The new manager is young, energetic, and full of fresh ideas."),
(1716,"enforce","v.","/In'fO:rs/","执行","Laws are meaningless if they are not properly enforced."),
(1717,"engage","v.","/In'geIdZ/","参与","The speaker engaged the audience with thought-provoking questions."),
(1718,"engineering","n.","/endZI'nIrIN/","工程学","Genetic engineering has the potential to cure many diseases."),
(1719,"engrave","v.","/In'greIv/","雕刻","His name was engraved on the trophy alongside previous winners."),
(1720,"enlighten","v.","/In'laIt@n/","启发","The documentary enlightened viewers about the plight of refugees."),
(1721,"enrich","v.","/In'rItS/","充实","Travel enriches the mind and broadens one's perspective."),
(1722,"enroll","v.","/In'roul/","注册","Over 500 students enrolled in the online course this semester."),
(1723,"ensue","v.","/In'su:/","接着发生","A heated debate ensued after the controversial remarks."),
(1724,"entail","v.","/In'teIl/","需要；必然导致","The job entails a great deal of international travel."),
(1725,"enterprise","n.","/'ent@rpraIz/","企业","She built a successful enterprise from a small workshop."),
(1726,"entertain","v.","/ent@r'teIn/","娱乐；★考虑","The committee is entertaining several proposals for the building."),
(1727,"enthusiasm","n.","/In'Tu:ziAz@m/","热情","His enthusiasm for the project motivated the whole team."),
(1728,"entity","n.","/'ent@ti/","实体","The company was treated as a separate legal entity."),
(1729,"entrepreneur","n.","/A:ntr@pr@'n3:r/","企业家","The young entrepreneur sold his startup for over $100 million."),
(1730,"envisage","v.","/In'vIzIdZ/","设想","The plan envisages the creation of over 10,000 new jobs."),
(1731,"envoy","n.","/'envOI/","使者","A special envoy was sent to mediate the peace negotiations."),
(1732,"epidemic","n./adj.","/epI'demIk/","流行病；流行的","Obesity has become an epidemic in many developed countries."),
(1733,"episode","n.","/'epIsoud/","片段","This episode focuses on climate change in the Arctic."),
(1734,"equip","v.","/I'kwIp/","装备","The soldiers were equipped with the latest body armor."),
(1735,"eradicate","v.","/I'rAdIkeIt/","根除","The organization aims to eradicate polio worldwide by 2025."),
(1736,"erect","v./adj.","/I'rekt/","建立；直立的","A statue was erected in his honor in the town square."),
(1737,"erode","v.","/I'roud/","侵蚀","Trust between the two sides has been steadily eroded."),
(1738,"erupt","v.","/I'r^pt/","爆发","Violence erupted after the controversial verdict was announced."),
(1739,"escalate","v.","/'esk@leIt/","升级","The dispute escalated into a full-scale conflict within weeks."),
(1740,"essence","n.","/'es@ns/","本质","The essence of the argument is that education should be free."),
]

lines = []
lines.append(f"## Big Day 10（词汇 1561-1740）")
lines.append("")
lines.append("| # | 单词 | 词性 | 音标 | 释义（★=熟词生义） | 例句 |")
lines.append("|---|------|------|------|-------------------|------|")
for num, word, pos, phon, defin, example in bd10:
    lines.append(f"| {num} | **{word}** | {pos} | {phon} | {defin} | {example} |")
lines.append("")

bak_path = r"C:\Users\方向容\Documents\408学习\408-学习管理\英语\考研词汇_词库.md"
with open(bak_path, "a", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"OK: appended Big Day 10 ({len(bd10)} words)")
